// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwXJ0zNecArglN9eK2-rTBOsaZTjAurKk',
    appId: '1:849376341106:web:a661523e780a7668c726eb',
    messagingSenderId: '849376341106',
    projectId: 'sns-bloc-firebase',
    authDomain: 'sns-bloc-firebase.firebaseapp.com',
    storageBucket: 'sns-bloc-firebase.appspot.com',
    measurementId: 'G-M10MP0VMDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmGHyt9ujSLz6Redn41Fo2ljrYmBsulgs',
    appId: '1:849376341106:android:209aa9aca332eb2ac726eb',
    messagingSenderId: '849376341106',
    projectId: 'sns-bloc-firebase',
    storageBucket: 'sns-bloc-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7WapHW5nQ83bXcRXRcKFx6kToWYG1lTE',
    appId: '1:849376341106:ios:8b76c9a7e34f31e3c726eb',
    messagingSenderId: '849376341106',
    projectId: 'sns-bloc-firebase',
    storageBucket: 'sns-bloc-firebase.appspot.com',
    iosBundleId: 'com.example.snsBlocFirebase',
  );
}
