// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env["FIREBASE_WEB_API_KEY"] ?? "",
    appId: dotenv.env["FIREBASE_WEB_PROJECT_ID"] ?? "",
    messagingSenderId: '849376341106',
    projectId: 'sns-bloc-firebase',
    authDomain: 'sns-bloc-firebase.firebaseapp.com',
    storageBucket: 'sns-bloc-firebase.appspot.com',
    measurementId: 'G-M10MP0VMDQ',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env["FIREBASE_ANDROID_API_KEY"] ?? "",
    appId: dotenv.env["FIREBASE_ANDROID_PROJECT_ID"] ?? "",
    messagingSenderId: '849376341106',
    projectId: 'sns-bloc-firebase',
    storageBucket: 'sns-bloc-firebase.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env["FIREBASE_IOS_API_KEY"] ?? "",
    appId: dotenv.env["FIREBASE_IOS_PROJECT_ID"] ?? "",
    messagingSenderId: '849376341106',
    projectId: 'sns-bloc-firebase',
    storageBucket: 'sns-bloc-firebase.appspot.com',
    iosBundleId: 'com.example.snsBlocFirebase',
  );
}
